apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-cluster-role
  labels:
    "app.kubernetes.io/name": 'jenkins-cluster-role'
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get","list","watch","patch", "update"]