apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc-nfs-storage
  namespace: jenkins
  labels:
    app: jeninks
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi